apiVersion: v1 
kind: Pod 
metadata: 
 name: pod-config 
spec:
  containers:
  - name: nginx 
    image: nginx 
    envFrom:
    - configMapRef:
        name: k8s-info

    # env: 
    # - name: course 
    #   valueFrom:
    #     configMapKeyRef:
    #       name: k8s-info
    #       key: course 
    # - name: trainer  
    #   valueFrom:
    #     configMapKeyRef:
    #       name: k8s-info
    #       key: trainer  


