apiVersion: apps/v1 
kind: ReplicaSet 
metadata: 
  name: nginx-replicas
   # these labels belongs to replicaset resource 
  labels:
    app: nginx
    tier: frontend
  spec:
   # modify replicas according to your case
    replicas: 2 
    selector: 
      matchLabels:
        app: nginx
        tier: frontend 
         # below is pod definition
    template: 
      metadata:
        labels:
          app: nginx
          tier: frontend 
          project: example-prj 
      spec:
        containers:
        - name: nginx 
          image: nginx:stable-perl

  

