apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    name: pod-1
    purpose: affinity
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
  labels:
    name: pod-2
    purpose: affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # hard rule pod-2 must and should running in pod-1 location of node 
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always

---
apiVersion: v1
kind: Pod
metadata:
  name: pod-3
  labels:
    name: pod-3
    purpose: affinity
spec:
  affinity:
     podAntiAffinity::
      requiredDuringSchedulingIgnoredDuringExecution: # hard rule pod-2 must and should running in pod-1 location of node 
      - labelSelector:
          matchExpressions:
          - key: name
            operator: In
            values:
            - pod-1
        topologyKey: "kubernetes.io/hostname"
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # keep this as always