apiVersion: v1
kind: PersistentVolume
metadata:
  name: ebs-static
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  csi: 
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: vol-sdsadw #change your volume id

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ebs-static
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  labels:
    purpose: ebs-static
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #claiming
    - name: ebs-static
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c #mention which availability zones using ur nodes
  volumes: #adding to the pods
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-static
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-static
    project: expense
  ports: 
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
