apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-dynamic
spec:
  storageClassName: "expense-ebs" # Empty string must be explicitly set otherwise default StorageClass will be set
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  labels:
    purpose: ebs-dynamic
    project: expense
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts: #claiming
    - name: ebs-dynamic
      mountPath: /usr/share/nginx/html
  nodeSelector:
    topology.kubernetes.io/zone: us-east-1c #mention which availability zones using ur nodes
  volumes: #adding to the pods
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: ebs-dynamic
---
apiVersion: v1 
kind: Service 
metadata:
  name: nginx-lb
spec:
  type: LoadBalancer
  selector:
    purpose: ebs-dynamic
    project: expense
  ports: 
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port